

# The necessary secrets are:
# - APP_URL - for preventing CORS errors
# - JWT_VERIFICATION_KEY - for Supabase @link https://supabase.com
#
# For local development, you can create a file called .dev.vars and use dotenv syntax.
#
# For deployed environments, you can use wrangler secrets to set these values.
# For example:
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
# Or use the Cloudflare web interface.
# @link https://developers.cloudflare.com/workers/platform/environment-variables/#environment-variables-via-the-dashboard
#




name = "astro-ai"

compatibility_date = "2023-01-01"
send_metrics = false
node_compat = true
route = "astro-ai-api.connection-tribe.net/*"
workers_dev = false
main = "src/worker.ts"
account_id = "02d7c2de135e5c6040973b6699cff32c"

[observability.logs]
enabled = false

# Production database
[[ d1_databases ]]
binding = "DB"
database_name = "astro-ai-prod-db"
database_id = "ac0deee4-21d5-4912-843f-b12fcd492736"
migrations_dir = "migrations"

# Development¯ environment
[env.dev]
name = "astro-ai-dev-env"
workers_dev = true
# route = "dev.astro-ai.connection-tribe.net/*"  # Uncomment if you want a dev subdomain